#!/bin/bash
#
# Benchmarks old-vs-new style fractional enumerations
#
# Copyright (c) 2022 Rudy Matela
# Distributed under the 3-Clause BSD license (see the file LICENSE)

for size in 5040 55440 720720 1441440 4324320 21621600
do
	for type in float double rational
	do
		for style in new old
		do
			echo -n "$style-$type $size "
			/usr/bin/time -f%e ./bench/list-fractionals $style-$type $size >/dev/null
		done
	done
done
